import type { Metadata } from 'next'
import '../styles/globals.css'
import '../styles/variables.css'
import { clsx } from 'clsx'
import { geistMono, geistSans } from '@/app/fonts'
import { TLayout } from '@/shared/types/layout'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: TLayout) {
    return (
        <html lang="en">
            <body className={clsx(geistSans.variable, geistMono.variable)}>
                {children}
            </body>
        </html>
    )
}
